### ISSUE TITLE
DD | Frontmatter, Introduction, Terminology

### ISSUE THREAD

**Issue by wgoodall01** [AtticATL/triage-app-team-1311#19]
- [Canvas Assignment](https://gatech.instructure.com/courses/232984/assignments/997962)
- [Requirements Doc](https://gatech.instructure.com/courses/232984/pages/detailed-design-document-and-instructions-iterative)
- [Example terminology page](https://gatech.instructure.com/courses/232984/pages/detailed-design-terminology)
- [Example front page](https://gatech.instructure.com/courses/232984/pages/detailed-design-front-page)

**Comment by wgoodall01** [comment]
Hey @nchap626 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/atticatl--team-1311-61dc61a4e8d2f00013f08371/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by flyntdubu** [comment]
Finished terminology section to the best of my ability, someone else check in to make sure all of my definitions make sense and i didnt miss anything major

**Comment by nchap626** [comment]
Intro is finished but needs review, one section on requirements left blank (awaiting group consensus before putting into writing)

**Comment by nchap626** [comment]
Requirements section is finished

**Comment by wgoodall01** [comment]
https://www.overleaf.com/read/rysxpjstgsvc
