### ISSUE TITLE
Description of Agile and our process last semester

### ISSUE THREAD

**Issue by wgoodall01** [AtticATL/triage-app-team-1311#23]
Last meeting, Dina asked for some writing, to include in a paper:

- A paragraph describing Agile Development
- A few paragraphs describing our planning process last semester

[Writing for Dr. Amin.docx](https://gtvault.sharepoint.com/:w:/s/1311TeamNameTBD/EbfeOGh2DQxAjaDyDUFLaOgB1tYda-ysnQCzqEyoXfsznA?e=kepzGp)

**Comment by wgoodall01** [comment]
Just wrote the few paragraphs for Dina, which we can send this Friday after the meeting.

Please give this a read and make any changes/edits/revisions that you see fit.

**Comment by flyntdubu** [comment]
Looks good to me!
