### ISSUE TITLE
Update iteration plan

### ISSUE THREAD

**Issue by wgoodall01** [AtticATL/triage-app-team-1311#26]
[Canvas assignment](https://gatech.instructure.com/courses/232984/assignments/998014)

> If you have iteration plan updates, please make them and post in you MS Teams General files with a filename that ends in "_sprint2-updated"
>
> Your iteration plan features will be used to grade you Sprint 2 demo videos. You should note any adjustments to the iteration plan in your demo video. You should also send the update to your client so that they are in the loop about any delay in feature delivery.
>
> Nothing is submitted via Canvas.

- Remove the URL transfer (in #7)
- Add the encryption story (in #29)

**Comment by nchap626** [comment]
No problem! Current charter is now up to date.
